# To run it in a Mac:
# TMPDIR=/private$TMPDIR docker-compose -f src/main/docker/localstack.yml up -d

version: '3.2'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_container
    ports:
      - '4563-4584:4563-4584'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_EXECUTION_ENV=True
    volumes:
      - '${TMPDIR:-/tmp/localstack}:/tmp'
      - '/var/run/docker.sock:/var/run/docker.sock'
